// Copyright 2026 The avapigw Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: operator/v1alpha1/config.proto

package operatorv1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HealthState represents the health state of a gateway.
type HealthState int32

const (
	HealthState_HEALTH_STATE_UNSPECIFIED HealthState = 0
	HealthState_HEALTH_STATE_HEALTHY     HealthState = 1
	HealthState_HEALTH_STATE_DEGRADED    HealthState = 2
	HealthState_HEALTH_STATE_UNHEALTHY   HealthState = 3
)

// Enum value maps for HealthState.
var (
	HealthState_name = map[int32]string{
		0: "HEALTH_STATE_UNSPECIFIED",
		1: "HEALTH_STATE_HEALTHY",
		2: "HEALTH_STATE_DEGRADED",
		3: "HEALTH_STATE_UNHEALTHY",
	}
	HealthState_value = map[string]int32{
		"HEALTH_STATE_UNSPECIFIED": 0,
		"HEALTH_STATE_HEALTHY":     1,
		"HEALTH_STATE_DEGRADED":    2,
		"HEALTH_STATE_UNHEALTHY":   3,
	}
)

func (x HealthState) Enum() *HealthState {
	p := new(HealthState)
	*p = x
	return p
}

func (x HealthState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthState) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_v1alpha1_config_proto_enumTypes[0].Descriptor()
}

func (HealthState) Type() protoreflect.EnumType {
	return &file_operator_v1alpha1_config_proto_enumTypes[0]
}

func (x HealthState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthState.Descriptor instead.
func (HealthState) EnumDescriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{0}
}

// ResourceType represents the type of configuration resource.
type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED  ResourceType = 0
	ResourceType_RESOURCE_TYPE_API_ROUTE    ResourceType = 1
	ResourceType_RESOURCE_TYPE_GRPC_ROUTE   ResourceType = 2
	ResourceType_RESOURCE_TYPE_BACKEND      ResourceType = 3
	ResourceType_RESOURCE_TYPE_GRPC_BACKEND ResourceType = 4
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RESOURCE_TYPE_API_ROUTE",
		2: "RESOURCE_TYPE_GRPC_ROUTE",
		3: "RESOURCE_TYPE_BACKEND",
		4: "RESOURCE_TYPE_GRPC_BACKEND",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED":  0,
		"RESOURCE_TYPE_API_ROUTE":    1,
		"RESOURCE_TYPE_GRPC_ROUTE":   2,
		"RESOURCE_TYPE_BACKEND":      3,
		"RESOURCE_TYPE_GRPC_BACKEND": 4,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_v1alpha1_config_proto_enumTypes[1].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_operator_v1alpha1_config_proto_enumTypes[1]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{1}
}

// UpdateType represents the type of configuration update.
type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_UNSPECIFIED UpdateType = 0
	// A resource was added.
	UpdateType_UPDATE_TYPE_ADDED UpdateType = 1
	// A resource was modified.
	UpdateType_UPDATE_TYPE_MODIFIED UpdateType = 2
	// A resource was deleted.
	UpdateType_UPDATE_TYPE_DELETED UpdateType = 3
	// Full configuration sync.
	UpdateType_UPDATE_TYPE_FULL_SYNC UpdateType = 4
	// Heartbeat/keep-alive message.
	UpdateType_UPDATE_TYPE_HEARTBEAT UpdateType = 5
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "UPDATE_TYPE_UNSPECIFIED",
		1: "UPDATE_TYPE_ADDED",
		2: "UPDATE_TYPE_MODIFIED",
		3: "UPDATE_TYPE_DELETED",
		4: "UPDATE_TYPE_FULL_SYNC",
		5: "UPDATE_TYPE_HEARTBEAT",
	}
	UpdateType_value = map[string]int32{
		"UPDATE_TYPE_UNSPECIFIED": 0,
		"UPDATE_TYPE_ADDED":       1,
		"UPDATE_TYPE_MODIFIED":    2,
		"UPDATE_TYPE_DELETED":     3,
		"UPDATE_TYPE_FULL_SYNC":   4,
		"UPDATE_TYPE_HEARTBEAT":   5,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_operator_v1alpha1_config_proto_enumTypes[2].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_operator_v1alpha1_config_proto_enumTypes[2]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{2}
}

// RegisterGatewayRequest contains gateway registration information.
type RegisterGatewayRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway information.
	Gateway *GatewayInfo `protobuf:"bytes,1,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Capabilities supported by this gateway.
	Capabilities  *GatewayCapabilities `protobuf:"bytes,2,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterGatewayRequest) Reset() {
	*x = RegisterGatewayRequest{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGatewayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGatewayRequest) ProtoMessage() {}

func (x *RegisterGatewayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGatewayRequest.ProtoReflect.Descriptor instead.
func (*RegisterGatewayRequest) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterGatewayRequest) GetGateway() *GatewayInfo {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *RegisterGatewayRequest) GetCapabilities() *GatewayCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// RegisterGatewayResponse contains the registration result.
type RegisterGatewayResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether registration was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if registration failed.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Session ID for this gateway connection.
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Initial configuration snapshot.
	InitialConfig *ConfigurationSnapshot `protobuf:"bytes,4,opt,name=initial_config,json=initialConfig,proto3" json:"initial_config,omitempty"`
	// Recommended heartbeat interval.
	HeartbeatInterval *durationpb.Duration `protobuf:"bytes,5,opt,name=heartbeat_interval,json=heartbeatInterval,proto3" json:"heartbeat_interval,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterGatewayResponse) Reset() {
	*x = RegisterGatewayResponse{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterGatewayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGatewayResponse) ProtoMessage() {}

func (x *RegisterGatewayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGatewayResponse.ProtoReflect.Descriptor instead.
func (*RegisterGatewayResponse) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterGatewayResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterGatewayResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterGatewayResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterGatewayResponse) GetInitialConfig() *ConfigurationSnapshot {
	if x != nil {
		return x.InitialConfig
	}
	return nil
}

func (x *RegisterGatewayResponse) GetHeartbeatInterval() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatInterval
	}
	return nil
}

// StreamConfigurationRequest initiates configuration streaming.
type StreamConfigurationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID from registration.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Gateway information.
	Gateway *GatewayInfo `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Last known configuration version (for resumption).
	LastConfigVersion string `protobuf:"bytes,3,opt,name=last_config_version,json=lastConfigVersion,proto3" json:"last_config_version,omitempty"`
	// Namespaces to watch (empty = all namespaces).
	Namespaces []string `protobuf:"bytes,4,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// Resource types to watch (empty = all types).
	ResourceTypes []ResourceType `protobuf:"varint,5,rep,packed,name=resource_types,json=resourceTypes,proto3,enum=avapigw.operator.v1alpha1.ResourceType" json:"resource_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamConfigurationRequest) Reset() {
	*x = StreamConfigurationRequest{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamConfigurationRequest) ProtoMessage() {}

func (x *StreamConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamConfigurationRequest.ProtoReflect.Descriptor instead.
func (*StreamConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{2}
}

func (x *StreamConfigurationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamConfigurationRequest) GetGateway() *GatewayInfo {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *StreamConfigurationRequest) GetLastConfigVersion() string {
	if x != nil {
		return x.LastConfigVersion
	}
	return ""
}

func (x *StreamConfigurationRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *StreamConfigurationRequest) GetResourceTypes() []ResourceType {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

// GetConfigurationRequest requests the current configuration snapshot.
type GetConfigurationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID from registration.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Gateway information.
	Gateway *GatewayInfo `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Namespaces to include (empty = all namespaces).
	Namespaces []string `protobuf:"bytes,3,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// Resource types to include (empty = all types).
	ResourceTypes []ResourceType `protobuf:"varint,4,rep,packed,name=resource_types,json=resourceTypes,proto3,enum=avapigw.operator.v1alpha1.ResourceType" json:"resource_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigurationRequest) Reset() {
	*x = GetConfigurationRequest{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigurationRequest) ProtoMessage() {}

func (x *GetConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigurationRequest.ProtoReflect.Descriptor instead.
func (*GetConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{3}
}

func (x *GetConfigurationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetConfigurationRequest) GetGateway() *GatewayInfo {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *GetConfigurationRequest) GetNamespaces() []string {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *GetConfigurationRequest) GetResourceTypes() []ResourceType {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

// HeartbeatRequest contains heartbeat information.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID from registration.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Gateway information.
	Gateway *GatewayInfo `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Current gateway status.
	Status *GatewayStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	// Last applied configuration version.
	LastAppliedVersion string `protobuf:"bytes,4,opt,name=last_applied_version,json=lastAppliedVersion,proto3" json:"last_applied_version,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HeartbeatRequest) GetGateway() *GatewayInfo {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *HeartbeatRequest) GetStatus() *GatewayStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *HeartbeatRequest) GetLastAppliedVersion() string {
	if x != nil {
		return x.LastAppliedVersion
	}
	return ""
}

// HeartbeatResponse contains heartbeat acknowledgment.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the heartbeat was acknowledged.
	Acknowledged bool `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Server timestamp.
	ServerTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	// Whether the gateway should reconnect (e.g., for config refresh).
	ShouldReconnect bool `protobuf:"varint,3,opt,name=should_reconnect,json=shouldReconnect,proto3" json:"should_reconnect,omitempty"`
	// Message from the operator.
	Message       string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{5}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

func (x *HeartbeatResponse) GetShouldReconnect() bool {
	if x != nil {
		return x.ShouldReconnect
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// AcknowledgeConfigurationRequest acknowledges a configuration update.
type AcknowledgeConfigurationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Session ID from registration.
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Gateway information.
	Gateway *GatewayInfo `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Configuration version being acknowledged.
	ConfigVersion string `protobuf:"bytes,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	// Whether the configuration was applied successfully.
	Success bool `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	// Error message if application failed.
	ErrorMessage string `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// Time taken to apply the configuration.
	ApplyDuration *durationpb.Duration `protobuf:"bytes,6,opt,name=apply_duration,json=applyDuration,proto3" json:"apply_duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeConfigurationRequest) Reset() {
	*x = AcknowledgeConfigurationRequest{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeConfigurationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeConfigurationRequest) ProtoMessage() {}

func (x *AcknowledgeConfigurationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeConfigurationRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeConfigurationRequest) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{6}
}

func (x *AcknowledgeConfigurationRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AcknowledgeConfigurationRequest) GetGateway() *GatewayInfo {
	if x != nil {
		return x.Gateway
	}
	return nil
}

func (x *AcknowledgeConfigurationRequest) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

func (x *AcknowledgeConfigurationRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcknowledgeConfigurationRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AcknowledgeConfigurationRequest) GetApplyDuration() *durationpb.Duration {
	if x != nil {
		return x.ApplyDuration
	}
	return nil
}

// AcknowledgeConfigurationResponse contains acknowledgment result.
type AcknowledgeConfigurationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the acknowledgment was received.
	Received bool `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	// Server timestamp.
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeConfigurationResponse) Reset() {
	*x = AcknowledgeConfigurationResponse{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeConfigurationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeConfigurationResponse) ProtoMessage() {}

func (x *AcknowledgeConfigurationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeConfigurationResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeConfigurationResponse) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{7}
}

func (x *AcknowledgeConfigurationResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *AcknowledgeConfigurationResponse) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

// GatewayInfo contains information about a gateway instance.
type GatewayInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Gateway namespace.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Gateway version.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Gateway pod name (if running in K8s).
	PodName string `protobuf:"bytes,4,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Gateway node name (if running in K8s).
	NodeName string `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	// Gateway labels.
	Labels map[string]string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Gateway annotations.
	Annotations   map[string]string `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayInfo) Reset() {
	*x = GatewayInfo{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayInfo) ProtoMessage() {}

func (x *GatewayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayInfo.ProtoReflect.Descriptor instead.
func (*GatewayInfo) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{8}
}

func (x *GatewayInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GatewayInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GatewayInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GatewayInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *GatewayInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *GatewayInfo) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *GatewayInfo) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

// GatewayCapabilities describes what features a gateway supports.
type GatewayCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Supports HTTP routes.
	HttpRoutes bool `protobuf:"varint,1,opt,name=http_routes,json=httpRoutes,proto3" json:"http_routes,omitempty"`
	// Supports gRPC routes.
	GrpcRoutes bool `protobuf:"varint,2,opt,name=grpc_routes,json=grpcRoutes,proto3" json:"grpc_routes,omitempty"`
	// Supports WebSocket.
	Websocket bool `protobuf:"varint,3,opt,name=websocket,proto3" json:"websocket,omitempty"`
	// Supports TLS termination.
	TlsTermination bool `protobuf:"varint,4,opt,name=tls_termination,json=tlsTermination,proto3" json:"tls_termination,omitempty"`
	// Supports mTLS.
	Mtls bool `protobuf:"varint,5,opt,name=mtls,proto3" json:"mtls,omitempty"`
	// Supports rate limiting.
	RateLimiting bool `protobuf:"varint,6,opt,name=rate_limiting,json=rateLimiting,proto3" json:"rate_limiting,omitempty"`
	// Supports circuit breaker.
	CircuitBreaker bool `protobuf:"varint,7,opt,name=circuit_breaker,json=circuitBreaker,proto3" json:"circuit_breaker,omitempty"`
	// Supports caching.
	Caching bool `protobuf:"varint,8,opt,name=caching,proto3" json:"caching,omitempty"`
	// Maximum configuration size in bytes.
	MaxConfigSize int64 `protobuf:"varint,9,opt,name=max_config_size,json=maxConfigSize,proto3" json:"max_config_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayCapabilities) Reset() {
	*x = GatewayCapabilities{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayCapabilities) ProtoMessage() {}

func (x *GatewayCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayCapabilities.ProtoReflect.Descriptor instead.
func (*GatewayCapabilities) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{9}
}

func (x *GatewayCapabilities) GetHttpRoutes() bool {
	if x != nil {
		return x.HttpRoutes
	}
	return false
}

func (x *GatewayCapabilities) GetGrpcRoutes() bool {
	if x != nil {
		return x.GrpcRoutes
	}
	return false
}

func (x *GatewayCapabilities) GetWebsocket() bool {
	if x != nil {
		return x.Websocket
	}
	return false
}

func (x *GatewayCapabilities) GetTlsTermination() bool {
	if x != nil {
		return x.TlsTermination
	}
	return false
}

func (x *GatewayCapabilities) GetMtls() bool {
	if x != nil {
		return x.Mtls
	}
	return false
}

func (x *GatewayCapabilities) GetRateLimiting() bool {
	if x != nil {
		return x.RateLimiting
	}
	return false
}

func (x *GatewayCapabilities) GetCircuitBreaker() bool {
	if x != nil {
		return x.CircuitBreaker
	}
	return false
}

func (x *GatewayCapabilities) GetCaching() bool {
	if x != nil {
		return x.Caching
	}
	return false
}

func (x *GatewayCapabilities) GetMaxConfigSize() int64 {
	if x != nil {
		return x.MaxConfigSize
	}
	return 0
}

// GatewayStatus contains the current status of a gateway.
type GatewayStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Gateway health state.
	Health HealthState `protobuf:"varint,1,opt,name=health,proto3,enum=avapigw.operator.v1alpha1.HealthState" json:"health,omitempty"`
	// Number of active connections.
	ActiveConnections int64 `protobuf:"varint,2,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	// Requests per second.
	RequestsPerSecond float64 `protobuf:"fixed64,3,opt,name=requests_per_second,json=requestsPerSecond,proto3" json:"requests_per_second,omitempty"`
	// Error rate (0-1).
	ErrorRate float64 `protobuf:"fixed64,4,opt,name=error_rate,json=errorRate,proto3" json:"error_rate,omitempty"`
	// Memory usage in bytes.
	MemoryBytes int64 `protobuf:"varint,5,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	// CPU usage (0-1).
	CpuUsage float64 `protobuf:"fixed64,6,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	// Uptime duration.
	Uptime *durationpb.Duration `protobuf:"bytes,7,opt,name=uptime,proto3" json:"uptime,omitempty"`
	// Last configuration applied timestamp.
	LastConfigApplied *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_config_applied,json=lastConfigApplied,proto3" json:"last_config_applied,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GatewayStatus) Reset() {
	*x = GatewayStatus{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayStatus) ProtoMessage() {}

func (x *GatewayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayStatus.ProtoReflect.Descriptor instead.
func (*GatewayStatus) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{10}
}

func (x *GatewayStatus) GetHealth() HealthState {
	if x != nil {
		return x.Health
	}
	return HealthState_HEALTH_STATE_UNSPECIFIED
}

func (x *GatewayStatus) GetActiveConnections() int64 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *GatewayStatus) GetRequestsPerSecond() float64 {
	if x != nil {
		return x.RequestsPerSecond
	}
	return 0
}

func (x *GatewayStatus) GetErrorRate() float64 {
	if x != nil {
		return x.ErrorRate
	}
	return 0
}

func (x *GatewayStatus) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *GatewayStatus) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GatewayStatus) GetUptime() *durationpb.Duration {
	if x != nil {
		return x.Uptime
	}
	return nil
}

func (x *GatewayStatus) GetLastConfigApplied() *timestamppb.Timestamp {
	if x != nil {
		return x.LastConfigApplied
	}
	return nil
}

// ConfigurationUpdate contains a configuration change notification.
type ConfigurationUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Update type.
	Type UpdateType `protobuf:"varint,1,opt,name=type,proto3,enum=avapigw.operator.v1alpha1.UpdateType" json:"type,omitempty"`
	// Configuration version (monotonically increasing).
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Timestamp of the update.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Resource that was updated.
	Resource *ConfigurationResource `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	// Full snapshot (for FULL_SYNC type).
	Snapshot *ConfigurationSnapshot `protobuf:"bytes,5,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// Sequence number for ordering.
	Sequence int64 `protobuf:"varint,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Whether this is the last update in a batch.
	IsLastInBatch bool `protobuf:"varint,7,opt,name=is_last_in_batch,json=isLastInBatch,proto3" json:"is_last_in_batch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationUpdate) Reset() {
	*x = ConfigurationUpdate{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationUpdate) ProtoMessage() {}

func (x *ConfigurationUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationUpdate.ProtoReflect.Descriptor instead.
func (*ConfigurationUpdate) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{11}
}

func (x *ConfigurationUpdate) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_UPDATE_TYPE_UNSPECIFIED
}

func (x *ConfigurationUpdate) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigurationUpdate) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ConfigurationUpdate) GetResource() *ConfigurationResource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *ConfigurationUpdate) GetSnapshot() *ConfigurationSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ConfigurationUpdate) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ConfigurationUpdate) GetIsLastInBatch() bool {
	if x != nil {
		return x.IsLastInBatch
	}
	return false
}

// ConfigurationResource represents a single configuration resource.
type ConfigurationResource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource type.
	Type ResourceType `protobuf:"varint,1,opt,name=type,proto3,enum=avapigw.operator.v1alpha1.ResourceType" json:"type,omitempty"`
	// Resource name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Resource namespace.
	Namespace string `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Resource version (Kubernetes resource version).
	ResourceVersion string `protobuf:"bytes,4,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// Resource generation.
	Generation int64 `protobuf:"varint,5,opt,name=generation,proto3" json:"generation,omitempty"`
	// Resource UID.
	Uid string `protobuf:"bytes,6,opt,name=uid,proto3" json:"uid,omitempty"`
	// Resource labels.
	Labels map[string]string `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource annotations.
	Annotations map[string]string `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Resource spec as JSON.
	SpecJson []byte `protobuf:"bytes,9,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	// Resource status as JSON.
	StatusJson []byte `protobuf:"bytes,10,opt,name=status_json,json=statusJson,proto3" json:"status_json,omitempty"`
	// Creation timestamp.
	CreationTimestamp *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ConfigurationResource) Reset() {
	*x = ConfigurationResource{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationResource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationResource) ProtoMessage() {}

func (x *ConfigurationResource) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationResource.ProtoReflect.Descriptor instead.
func (*ConfigurationResource) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigurationResource) GetType() ResourceType {
	if x != nil {
		return x.Type
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *ConfigurationResource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigurationResource) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ConfigurationResource) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *ConfigurationResource) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ConfigurationResource) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ConfigurationResource) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ConfigurationResource) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ConfigurationResource) GetSpecJson() []byte {
	if x != nil {
		return x.SpecJson
	}
	return nil
}

func (x *ConfigurationResource) GetStatusJson() []byte {
	if x != nil {
		return x.StatusJson
	}
	return nil
}

func (x *ConfigurationResource) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

// ConfigurationSnapshot contains the complete configuration state.
type ConfigurationSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Snapshot version.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Timestamp when the snapshot was created.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// API routes.
	ApiRoutes []*ConfigurationResource `protobuf:"bytes,3,rep,name=api_routes,json=apiRoutes,proto3" json:"api_routes,omitempty"`
	// gRPC routes.
	GrpcRoutes []*ConfigurationResource `protobuf:"bytes,4,rep,name=grpc_routes,json=grpcRoutes,proto3" json:"grpc_routes,omitempty"`
	// HTTP backends.
	Backends []*ConfigurationResource `protobuf:"bytes,5,rep,name=backends,proto3" json:"backends,omitempty"`
	// gRPC backends.
	GrpcBackends []*ConfigurationResource `protobuf:"bytes,6,rep,name=grpc_backends,json=grpcBackends,proto3" json:"grpc_backends,omitempty"`
	// Total number of resources.
	TotalResources int32 `protobuf:"varint,7,opt,name=total_resources,json=totalResources,proto3" json:"total_resources,omitempty"`
	// Checksum of the configuration (for validation).
	Checksum      string `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigurationSnapshot) Reset() {
	*x = ConfigurationSnapshot{}
	mi := &file_operator_v1alpha1_config_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigurationSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigurationSnapshot) ProtoMessage() {}

func (x *ConfigurationSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_operator_v1alpha1_config_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigurationSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigurationSnapshot) Descriptor() ([]byte, []int) {
	return file_operator_v1alpha1_config_proto_rawDescGZIP(), []int{13}
}

func (x *ConfigurationSnapshot) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ConfigurationSnapshot) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ConfigurationSnapshot) GetApiRoutes() []*ConfigurationResource {
	if x != nil {
		return x.ApiRoutes
	}
	return nil
}

func (x *ConfigurationSnapshot) GetGrpcRoutes() []*ConfigurationResource {
	if x != nil {
		return x.GrpcRoutes
	}
	return nil
}

func (x *ConfigurationSnapshot) GetBackends() []*ConfigurationResource {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *ConfigurationSnapshot) GetGrpcBackends() []*ConfigurationResource {
	if x != nil {
		return x.GrpcBackends
	}
	return nil
}

func (x *ConfigurationSnapshot) GetTotalResources() int32 {
	if x != nil {
		return x.TotalResources
	}
	return 0
}

func (x *ConfigurationSnapshot) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

var File_operator_v1alpha1_config_proto protoreflect.FileDescriptor

const file_operator_v1alpha1_config_proto_rawDesc = "" +
	"\n" +
	"\x1eoperator/v1alpha1/config.proto\x12\x19avapigw.operator.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\xae\x01\n" +
	"\x16RegisterGatewayRequest\x12@\n" +
	"\agateway\x18\x01 \x01(\v2&.avapigw.operator.v1alpha1.GatewayInfoR\agateway\x12R\n" +
	"\fcapabilities\x18\x02 \x01(\v2..avapigw.operator.v1alpha1.GatewayCapabilitiesR\fcapabilities\"\x9a\x02\n" +
	"\x17RegisterGatewayResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12W\n" +
	"\x0einitial_config\x18\x04 \x01(\v20.avapigw.operator.v1alpha1.ConfigurationSnapshotR\rinitialConfig\x12H\n" +
	"\x12heartbeat_interval\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x11heartbeatInterval\"\x9d\x02\n" +
	"\x1aStreamConfigurationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12@\n" +
	"\agateway\x18\x02 \x01(\v2&.avapigw.operator.v1alpha1.GatewayInfoR\agateway\x12.\n" +
	"\x13last_config_version\x18\x03 \x01(\tR\x11lastConfigVersion\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x04 \x03(\tR\n" +
	"namespaces\x12N\n" +
	"\x0eresource_types\x18\x05 \x03(\x0e2'.avapigw.operator.v1alpha1.ResourceTypeR\rresourceTypes\"\xea\x01\n" +
	"\x17GetConfigurationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12@\n" +
	"\agateway\x18\x02 \x01(\v2&.avapigw.operator.v1alpha1.GatewayInfoR\agateway\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x03 \x03(\tR\n" +
	"namespaces\x12N\n" +
	"\x0eresource_types\x18\x04 \x03(\x0e2'.avapigw.operator.v1alpha1.ResourceTypeR\rresourceTypes\"\xe7\x01\n" +
	"\x10HeartbeatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12@\n" +
	"\agateway\x18\x02 \x01(\v2&.avapigw.operator.v1alpha1.GatewayInfoR\agateway\x12@\n" +
	"\x06status\x18\x03 \x01(\v2(.avapigw.operator.v1alpha1.GatewayStatusR\x06status\x120\n" +
	"\x14last_applied_version\x18\x04 \x01(\tR\x12lastAppliedVersion\"\xb9\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\x12)\n" +
	"\x10should_reconnect\x18\x03 \x01(\bR\x0fshouldReconnect\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xaa\x02\n" +
	"\x1fAcknowledgeConfigurationRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12@\n" +
	"\agateway\x18\x02 \x01(\v2&.avapigw.operator.v1alpha1.GatewayInfoR\agateway\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\tR\rconfigVersion\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12@\n" +
	"\x0eapply_duration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\rapplyDuration\"{\n" +
	" AcknowledgeConfigurationResponse\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12;\n" +
	"\vserver_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime\"\xb3\x03\n" +
	"\vGatewayInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x19\n" +
	"\bpod_name\x18\x04 \x01(\tR\apodName\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\x12J\n" +
	"\x06labels\x18\x06 \x03(\v22.avapigw.operator.v1alpha1.GatewayInfo.LabelsEntryR\x06labels\x12Y\n" +
	"\vannotations\x18\a \x03(\v27.avapigw.operator.v1alpha1.GatewayInfo.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc2\x02\n" +
	"\x13GatewayCapabilities\x12\x1f\n" +
	"\vhttp_routes\x18\x01 \x01(\bR\n" +
	"httpRoutes\x12\x1f\n" +
	"\vgrpc_routes\x18\x02 \x01(\bR\n" +
	"grpcRoutes\x12\x1c\n" +
	"\twebsocket\x18\x03 \x01(\bR\twebsocket\x12'\n" +
	"\x0ftls_termination\x18\x04 \x01(\bR\x0etlsTermination\x12\x12\n" +
	"\x04mtls\x18\x05 \x01(\bR\x04mtls\x12#\n" +
	"\rrate_limiting\x18\x06 \x01(\bR\frateLimiting\x12'\n" +
	"\x0fcircuit_breaker\x18\a \x01(\bR\x0ecircuitBreaker\x12\x18\n" +
	"\acaching\x18\b \x01(\bR\acaching\x12&\n" +
	"\x0fmax_config_size\x18\t \x01(\x03R\rmaxConfigSize\"\x8c\x03\n" +
	"\rGatewayStatus\x12>\n" +
	"\x06health\x18\x01 \x01(\x0e2&.avapigw.operator.v1alpha1.HealthStateR\x06health\x12-\n" +
	"\x12active_connections\x18\x02 \x01(\x03R\x11activeConnections\x12.\n" +
	"\x13requests_per_second\x18\x03 \x01(\x01R\x11requestsPerSecond\x12\x1d\n" +
	"\n" +
	"error_rate\x18\x04 \x01(\x01R\terrorRate\x12!\n" +
	"\fmemory_bytes\x18\x05 \x01(\x03R\vmemoryBytes\x12\x1b\n" +
	"\tcpu_usage\x18\x06 \x01(\x01R\bcpuUsage\x121\n" +
	"\x06uptime\x18\a \x01(\v2\x19.google.protobuf.DurationR\x06uptime\x12J\n" +
	"\x13last_config_applied\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x11lastConfigApplied\"\x85\x03\n" +
	"\x13ConfigurationUpdate\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.avapigw.operator.v1alpha1.UpdateTypeR\x04type\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12L\n" +
	"\bresource\x18\x04 \x01(\v20.avapigw.operator.v1alpha1.ConfigurationResourceR\bresource\x12L\n" +
	"\bsnapshot\x18\x05 \x01(\v20.avapigw.operator.v1alpha1.ConfigurationSnapshotR\bsnapshot\x12\x1a\n" +
	"\bsequence\x18\x06 \x01(\x03R\bsequence\x12'\n" +
	"\x10is_last_in_batch\x18\a \x01(\bR\risLastInBatch\"\xa2\x05\n" +
	"\x15ConfigurationResource\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2'.avapigw.operator.v1alpha1.ResourceTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12)\n" +
	"\x10resource_version\x18\x04 \x01(\tR\x0fresourceVersion\x12\x1e\n" +
	"\n" +
	"generation\x18\x05 \x01(\x03R\n" +
	"generation\x12\x10\n" +
	"\x03uid\x18\x06 \x01(\tR\x03uid\x12T\n" +
	"\x06labels\x18\a \x03(\v2<.avapigw.operator.v1alpha1.ConfigurationResource.LabelsEntryR\x06labels\x12c\n" +
	"\vannotations\x18\b \x03(\v2A.avapigw.operator.v1alpha1.ConfigurationResource.AnnotationsEntryR\vannotations\x12\x1b\n" +
	"\tspec_json\x18\t \x01(\fR\bspecJson\x12\x1f\n" +
	"\vstatus_json\x18\n" +
	" \x01(\fR\n" +
	"statusJson\x12I\n" +
	"\x12creation_timestamp\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x11creationTimestamp\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x03\n" +
	"\x15ConfigurationSnapshot\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12O\n" +
	"\n" +
	"api_routes\x18\x03 \x03(\v20.avapigw.operator.v1alpha1.ConfigurationResourceR\tapiRoutes\x12Q\n" +
	"\vgrpc_routes\x18\x04 \x03(\v20.avapigw.operator.v1alpha1.ConfigurationResourceR\n" +
	"grpcRoutes\x12L\n" +
	"\bbackends\x18\x05 \x03(\v20.avapigw.operator.v1alpha1.ConfigurationResourceR\bbackends\x12U\n" +
	"\rgrpc_backends\x18\x06 \x03(\v20.avapigw.operator.v1alpha1.ConfigurationResourceR\fgrpcBackends\x12'\n" +
	"\x0ftotal_resources\x18\a \x01(\x05R\x0etotalResources\x12\x1a\n" +
	"\bchecksum\x18\b \x01(\tR\bchecksum*|\n" +
	"\vHealthState\x12\x1c\n" +
	"\x18HEALTH_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14HEALTH_STATE_HEALTHY\x10\x01\x12\x19\n" +
	"\x15HEALTH_STATE_DEGRADED\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATE_UNHEALTHY\x10\x03*\xa3\x01\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RESOURCE_TYPE_API_ROUTE\x10\x01\x12\x1c\n" +
	"\x18RESOURCE_TYPE_GRPC_ROUTE\x10\x02\x12\x19\n" +
	"\x15RESOURCE_TYPE_BACKEND\x10\x03\x12\x1e\n" +
	"\x1aRESOURCE_TYPE_GRPC_BACKEND\x10\x04*\xa9\x01\n" +
	"\n" +
	"UpdateType\x12\x1b\n" +
	"\x17UPDATE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11UPDATE_TYPE_ADDED\x10\x01\x12\x18\n" +
	"\x14UPDATE_TYPE_MODIFIED\x10\x02\x12\x17\n" +
	"\x13UPDATE_TYPE_DELETED\x10\x03\x12\x19\n" +
	"\x15UPDATE_TYPE_FULL_SYNC\x10\x04\x12\x19\n" +
	"\x15UPDATE_TYPE_HEARTBEAT\x10\x052\x88\x05\n" +
	"\x14ConfigurationService\x12x\n" +
	"\x0fRegisterGateway\x121.avapigw.operator.v1alpha1.RegisterGatewayRequest\x1a2.avapigw.operator.v1alpha1.RegisterGatewayResponse\x12~\n" +
	"\x13StreamConfiguration\x125.avapigw.operator.v1alpha1.StreamConfigurationRequest\x1a..avapigw.operator.v1alpha1.ConfigurationUpdate0\x01\x12x\n" +
	"\x10GetConfiguration\x122.avapigw.operator.v1alpha1.GetConfigurationRequest\x1a0.avapigw.operator.v1alpha1.ConfigurationSnapshot\x12f\n" +
	"\tHeartbeat\x12+.avapigw.operator.v1alpha1.HeartbeatRequest\x1a,.avapigw.operator.v1alpha1.HeartbeatResponse\x12\x93\x01\n" +
	"\x18AcknowledgeConfiguration\x12:.avapigw.operator.v1alpha1.AcknowledgeConfigurationRequest\x1a;.avapigw.operator.v1alpha1.AcknowledgeConfigurationResponseBKZIgithub.com/vyrodovalexey/avapigw/proto/operator/v1alpha1;operatorv1alpha1b\x06proto3"

var (
	file_operator_v1alpha1_config_proto_rawDescOnce sync.Once
	file_operator_v1alpha1_config_proto_rawDescData []byte
)

func file_operator_v1alpha1_config_proto_rawDescGZIP() []byte {
	file_operator_v1alpha1_config_proto_rawDescOnce.Do(func() {
		file_operator_v1alpha1_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_operator_v1alpha1_config_proto_rawDesc), len(file_operator_v1alpha1_config_proto_rawDesc)))
	})
	return file_operator_v1alpha1_config_proto_rawDescData
}

var file_operator_v1alpha1_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_operator_v1alpha1_config_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_operator_v1alpha1_config_proto_goTypes = []any{
	(HealthState)(0),                         // 0: avapigw.operator.v1alpha1.HealthState
	(ResourceType)(0),                        // 1: avapigw.operator.v1alpha1.ResourceType
	(UpdateType)(0),                          // 2: avapigw.operator.v1alpha1.UpdateType
	(*RegisterGatewayRequest)(nil),           // 3: avapigw.operator.v1alpha1.RegisterGatewayRequest
	(*RegisterGatewayResponse)(nil),          // 4: avapigw.operator.v1alpha1.RegisterGatewayResponse
	(*StreamConfigurationRequest)(nil),       // 5: avapigw.operator.v1alpha1.StreamConfigurationRequest
	(*GetConfigurationRequest)(nil),          // 6: avapigw.operator.v1alpha1.GetConfigurationRequest
	(*HeartbeatRequest)(nil),                 // 7: avapigw.operator.v1alpha1.HeartbeatRequest
	(*HeartbeatResponse)(nil),                // 8: avapigw.operator.v1alpha1.HeartbeatResponse
	(*AcknowledgeConfigurationRequest)(nil),  // 9: avapigw.operator.v1alpha1.AcknowledgeConfigurationRequest
	(*AcknowledgeConfigurationResponse)(nil), // 10: avapigw.operator.v1alpha1.AcknowledgeConfigurationResponse
	(*GatewayInfo)(nil),                      // 11: avapigw.operator.v1alpha1.GatewayInfo
	(*GatewayCapabilities)(nil),              // 12: avapigw.operator.v1alpha1.GatewayCapabilities
	(*GatewayStatus)(nil),                    // 13: avapigw.operator.v1alpha1.GatewayStatus
	(*ConfigurationUpdate)(nil),              // 14: avapigw.operator.v1alpha1.ConfigurationUpdate
	(*ConfigurationResource)(nil),            // 15: avapigw.operator.v1alpha1.ConfigurationResource
	(*ConfigurationSnapshot)(nil),            // 16: avapigw.operator.v1alpha1.ConfigurationSnapshot
	nil,                                      // 17: avapigw.operator.v1alpha1.GatewayInfo.LabelsEntry
	nil,                                      // 18: avapigw.operator.v1alpha1.GatewayInfo.AnnotationsEntry
	nil,                                      // 19: avapigw.operator.v1alpha1.ConfigurationResource.LabelsEntry
	nil,                                      // 20: avapigw.operator.v1alpha1.ConfigurationResource.AnnotationsEntry
	(*durationpb.Duration)(nil),              // 21: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),            // 22: google.protobuf.Timestamp
}
var file_operator_v1alpha1_config_proto_depIdxs = []int32{
	11, // 0: avapigw.operator.v1alpha1.RegisterGatewayRequest.gateway:type_name -> avapigw.operator.v1alpha1.GatewayInfo
	12, // 1: avapigw.operator.v1alpha1.RegisterGatewayRequest.capabilities:type_name -> avapigw.operator.v1alpha1.GatewayCapabilities
	16, // 2: avapigw.operator.v1alpha1.RegisterGatewayResponse.initial_config:type_name -> avapigw.operator.v1alpha1.ConfigurationSnapshot
	21, // 3: avapigw.operator.v1alpha1.RegisterGatewayResponse.heartbeat_interval:type_name -> google.protobuf.Duration
	11, // 4: avapigw.operator.v1alpha1.StreamConfigurationRequest.gateway:type_name -> avapigw.operator.v1alpha1.GatewayInfo
	1,  // 5: avapigw.operator.v1alpha1.StreamConfigurationRequest.resource_types:type_name -> avapigw.operator.v1alpha1.ResourceType
	11, // 6: avapigw.operator.v1alpha1.GetConfigurationRequest.gateway:type_name -> avapigw.operator.v1alpha1.GatewayInfo
	1,  // 7: avapigw.operator.v1alpha1.GetConfigurationRequest.resource_types:type_name -> avapigw.operator.v1alpha1.ResourceType
	11, // 8: avapigw.operator.v1alpha1.HeartbeatRequest.gateway:type_name -> avapigw.operator.v1alpha1.GatewayInfo
	13, // 9: avapigw.operator.v1alpha1.HeartbeatRequest.status:type_name -> avapigw.operator.v1alpha1.GatewayStatus
	22, // 10: avapigw.operator.v1alpha1.HeartbeatResponse.server_time:type_name -> google.protobuf.Timestamp
	11, // 11: avapigw.operator.v1alpha1.AcknowledgeConfigurationRequest.gateway:type_name -> avapigw.operator.v1alpha1.GatewayInfo
	21, // 12: avapigw.operator.v1alpha1.AcknowledgeConfigurationRequest.apply_duration:type_name -> google.protobuf.Duration
	22, // 13: avapigw.operator.v1alpha1.AcknowledgeConfigurationResponse.server_time:type_name -> google.protobuf.Timestamp
	17, // 14: avapigw.operator.v1alpha1.GatewayInfo.labels:type_name -> avapigw.operator.v1alpha1.GatewayInfo.LabelsEntry
	18, // 15: avapigw.operator.v1alpha1.GatewayInfo.annotations:type_name -> avapigw.operator.v1alpha1.GatewayInfo.AnnotationsEntry
	0,  // 16: avapigw.operator.v1alpha1.GatewayStatus.health:type_name -> avapigw.operator.v1alpha1.HealthState
	21, // 17: avapigw.operator.v1alpha1.GatewayStatus.uptime:type_name -> google.protobuf.Duration
	22, // 18: avapigw.operator.v1alpha1.GatewayStatus.last_config_applied:type_name -> google.protobuf.Timestamp
	2,  // 19: avapigw.operator.v1alpha1.ConfigurationUpdate.type:type_name -> avapigw.operator.v1alpha1.UpdateType
	22, // 20: avapigw.operator.v1alpha1.ConfigurationUpdate.timestamp:type_name -> google.protobuf.Timestamp
	15, // 21: avapigw.operator.v1alpha1.ConfigurationUpdate.resource:type_name -> avapigw.operator.v1alpha1.ConfigurationResource
	16, // 22: avapigw.operator.v1alpha1.ConfigurationUpdate.snapshot:type_name -> avapigw.operator.v1alpha1.ConfigurationSnapshot
	1,  // 23: avapigw.operator.v1alpha1.ConfigurationResource.type:type_name -> avapigw.operator.v1alpha1.ResourceType
	19, // 24: avapigw.operator.v1alpha1.ConfigurationResource.labels:type_name -> avapigw.operator.v1alpha1.ConfigurationResource.LabelsEntry
	20, // 25: avapigw.operator.v1alpha1.ConfigurationResource.annotations:type_name -> avapigw.operator.v1alpha1.ConfigurationResource.AnnotationsEntry
	22, // 26: avapigw.operator.v1alpha1.ConfigurationResource.creation_timestamp:type_name -> google.protobuf.Timestamp
	22, // 27: avapigw.operator.v1alpha1.ConfigurationSnapshot.timestamp:type_name -> google.protobuf.Timestamp
	15, // 28: avapigw.operator.v1alpha1.ConfigurationSnapshot.api_routes:type_name -> avapigw.operator.v1alpha1.ConfigurationResource
	15, // 29: avapigw.operator.v1alpha1.ConfigurationSnapshot.grpc_routes:type_name -> avapigw.operator.v1alpha1.ConfigurationResource
	15, // 30: avapigw.operator.v1alpha1.ConfigurationSnapshot.backends:type_name -> avapigw.operator.v1alpha1.ConfigurationResource
	15, // 31: avapigw.operator.v1alpha1.ConfigurationSnapshot.grpc_backends:type_name -> avapigw.operator.v1alpha1.ConfigurationResource
	3,  // 32: avapigw.operator.v1alpha1.ConfigurationService.RegisterGateway:input_type -> avapigw.operator.v1alpha1.RegisterGatewayRequest
	5,  // 33: avapigw.operator.v1alpha1.ConfigurationService.StreamConfiguration:input_type -> avapigw.operator.v1alpha1.StreamConfigurationRequest
	6,  // 34: avapigw.operator.v1alpha1.ConfigurationService.GetConfiguration:input_type -> avapigw.operator.v1alpha1.GetConfigurationRequest
	7,  // 35: avapigw.operator.v1alpha1.ConfigurationService.Heartbeat:input_type -> avapigw.operator.v1alpha1.HeartbeatRequest
	9,  // 36: avapigw.operator.v1alpha1.ConfigurationService.AcknowledgeConfiguration:input_type -> avapigw.operator.v1alpha1.AcknowledgeConfigurationRequest
	4,  // 37: avapigw.operator.v1alpha1.ConfigurationService.RegisterGateway:output_type -> avapigw.operator.v1alpha1.RegisterGatewayResponse
	14, // 38: avapigw.operator.v1alpha1.ConfigurationService.StreamConfiguration:output_type -> avapigw.operator.v1alpha1.ConfigurationUpdate
	16, // 39: avapigw.operator.v1alpha1.ConfigurationService.GetConfiguration:output_type -> avapigw.operator.v1alpha1.ConfigurationSnapshot
	8,  // 40: avapigw.operator.v1alpha1.ConfigurationService.Heartbeat:output_type -> avapigw.operator.v1alpha1.HeartbeatResponse
	10, // 41: avapigw.operator.v1alpha1.ConfigurationService.AcknowledgeConfiguration:output_type -> avapigw.operator.v1alpha1.AcknowledgeConfigurationResponse
	37, // [37:42] is the sub-list for method output_type
	32, // [32:37] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_operator_v1alpha1_config_proto_init() }
func file_operator_v1alpha1_config_proto_init() {
	if File_operator_v1alpha1_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_operator_v1alpha1_config_proto_rawDesc), len(file_operator_v1alpha1_config_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_operator_v1alpha1_config_proto_goTypes,
		DependencyIndexes: file_operator_v1alpha1_config_proto_depIdxs,
		EnumInfos:         file_operator_v1alpha1_config_proto_enumTypes,
		MessageInfos:      file_operator_v1alpha1_config_proto_msgTypes,
	}.Build()
	File_operator_v1alpha1_config_proto = out.File
	file_operator_v1alpha1_config_proto_goTypes = nil
	file_operator_v1alpha1_config_proto_depIdxs = nil
}
