// Copyright 2026 The avapigw Authors.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: operator/v1alpha1/config.proto

package operatorv1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigurationService_RegisterGateway_FullMethodName          = "/avapigw.operator.v1alpha1.ConfigurationService/RegisterGateway"
	ConfigurationService_StreamConfiguration_FullMethodName      = "/avapigw.operator.v1alpha1.ConfigurationService/StreamConfiguration"
	ConfigurationService_GetConfiguration_FullMethodName         = "/avapigw.operator.v1alpha1.ConfigurationService/GetConfiguration"
	ConfigurationService_Heartbeat_FullMethodName                = "/avapigw.operator.v1alpha1.ConfigurationService/Heartbeat"
	ConfigurationService_AcknowledgeConfiguration_FullMethodName = "/avapigw.operator.v1alpha1.ConfigurationService/AcknowledgeConfiguration"
)

// ConfigurationServiceClient is the client API for ConfigurationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigurationService provides configuration management for API gateways.
// The operator pushes configuration updates to connected gateways via streaming.
type ConfigurationServiceClient interface {
	// RegisterGateway registers a gateway instance with the operator.
	// Returns the initial configuration snapshot.
	RegisterGateway(ctx context.Context, in *RegisterGatewayRequest, opts ...grpc.CallOption) (*RegisterGatewayResponse, error)
	// StreamConfiguration establishes a server-side streaming connection
	// for receiving configuration updates from the operator.
	StreamConfiguration(ctx context.Context, in *StreamConfigurationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigurationUpdate], error)
	// GetConfiguration returns the current configuration snapshot.
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationSnapshot, error)
	// Heartbeat sends a keep-alive signal to the operator.
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
	// AcknowledgeConfiguration acknowledges receipt and application of a configuration update.
	AcknowledgeConfiguration(ctx context.Context, in *AcknowledgeConfigurationRequest, opts ...grpc.CallOption) (*AcknowledgeConfigurationResponse, error)
}

type configurationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationServiceClient(cc grpc.ClientConnInterface) ConfigurationServiceClient {
	return &configurationServiceClient{cc}
}

func (c *configurationServiceClient) RegisterGateway(ctx context.Context, in *RegisterGatewayRequest, opts ...grpc.CallOption) (*RegisterGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterGatewayResponse)
	err := c.cc.Invoke(ctx, ConfigurationService_RegisterGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationServiceClient) StreamConfiguration(ctx context.Context, in *StreamConfigurationRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ConfigurationUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigurationService_ServiceDesc.Streams[0], ConfigurationService_StreamConfiguration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamConfigurationRequest, ConfigurationUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigurationService_StreamConfigurationClient = grpc.ServerStreamingClient[ConfigurationUpdate]

func (c *configurationServiceClient) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*ConfigurationSnapshot, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigurationSnapshot)
	err := c.cc.Invoke(ctx, ConfigurationService_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, ConfigurationService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configurationServiceClient) AcknowledgeConfiguration(ctx context.Context, in *AcknowledgeConfigurationRequest, opts ...grpc.CallOption) (*AcknowledgeConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeConfigurationResponse)
	err := c.cc.Invoke(ctx, ConfigurationService_AcknowledgeConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationServiceServer is the server API for ConfigurationService service.
// All implementations must embed UnimplementedConfigurationServiceServer
// for forward compatibility.
//
// ConfigurationService provides configuration management for API gateways.
// The operator pushes configuration updates to connected gateways via streaming.
type ConfigurationServiceServer interface {
	// RegisterGateway registers a gateway instance with the operator.
	// Returns the initial configuration snapshot.
	RegisterGateway(context.Context, *RegisterGatewayRequest) (*RegisterGatewayResponse, error)
	// StreamConfiguration establishes a server-side streaming connection
	// for receiving configuration updates from the operator.
	StreamConfiguration(*StreamConfigurationRequest, grpc.ServerStreamingServer[ConfigurationUpdate]) error
	// GetConfiguration returns the current configuration snapshot.
	GetConfiguration(context.Context, *GetConfigurationRequest) (*ConfigurationSnapshot, error)
	// Heartbeat sends a keep-alive signal to the operator.
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	// AcknowledgeConfiguration acknowledges receipt and application of a configuration update.
	AcknowledgeConfiguration(context.Context, *AcknowledgeConfigurationRequest) (*AcknowledgeConfigurationResponse, error)
	mustEmbedUnimplementedConfigurationServiceServer()
}

// UnimplementedConfigurationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigurationServiceServer struct{}

func (UnimplementedConfigurationServiceServer) RegisterGateway(context.Context, *RegisterGatewayRequest) (*RegisterGatewayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterGateway not implemented")
}
func (UnimplementedConfigurationServiceServer) StreamConfiguration(*StreamConfigurationRequest, grpc.ServerStreamingServer[ConfigurationUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamConfiguration not implemented")
}
func (UnimplementedConfigurationServiceServer) GetConfiguration(context.Context, *GetConfigurationRequest) (*ConfigurationSnapshot, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedConfigurationServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedConfigurationServiceServer) AcknowledgeConfiguration(context.Context, *AcknowledgeConfigurationRequest) (*AcknowledgeConfigurationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcknowledgeConfiguration not implemented")
}
func (UnimplementedConfigurationServiceServer) mustEmbedUnimplementedConfigurationServiceServer() {}
func (UnimplementedConfigurationServiceServer) testEmbeddedByValue()                              {}

// UnsafeConfigurationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationServiceServer will
// result in compilation errors.
type UnsafeConfigurationServiceServer interface {
	mustEmbedUnimplementedConfigurationServiceServer()
}

func RegisterConfigurationServiceServer(s grpc.ServiceRegistrar, srv ConfigurationServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigurationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigurationService_ServiceDesc, srv)
}

func _ConfigurationService_RegisterGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).RegisterGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_RegisterGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).RegisterGateway(ctx, req.(*RegisterGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationService_StreamConfiguration_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamConfigurationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigurationServiceServer).StreamConfiguration(m, &grpc.GenericServerStream[StreamConfigurationRequest, ConfigurationUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigurationService_StreamConfigurationServer = grpc.ServerStreamingServer[ConfigurationUpdate]

func _ConfigurationService_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).GetConfiguration(ctx, req.(*GetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConfigurationService_AcknowledgeConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationServiceServer).AcknowledgeConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationService_AcknowledgeConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationServiceServer).AcknowledgeConfiguration(ctx, req.(*AcknowledgeConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigurationService_ServiceDesc is the grpc.ServiceDesc for ConfigurationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigurationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "avapigw.operator.v1alpha1.ConfigurationService",
	HandlerType: (*ConfigurationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterGateway",
			Handler:    _ConfigurationService_RegisterGateway_Handler,
		},
		{
			MethodName: "GetConfiguration",
			Handler:    _ConfigurationService_GetConfiguration_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _ConfigurationService_Heartbeat_Handler,
		},
		{
			MethodName: "AcknowledgeConfiguration",
			Handler:    _ConfigurationService_AcknowledgeConfiguration_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConfiguration",
			Handler:       _ConfigurationService_StreamConfiguration_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "operator/v1alpha1/config.proto",
}
