version: "2"

run:
  timeout: 5m
  tests: false

linters:
  default: none
  enable:
    # Code correctness
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - bodyclose
    - noctx
    - sqlclosecheck
    # Security
    - gosec
    - bidichk
    # Code style
    - goconst
    - unconvert
    - asciicheck
    - goheader
    - whitespace
    - goprintffuncname
    - misspell
    # Complexity
    - gocognit
    - gocyclo
    - funlen
    - nestif
    # Best practices
    - lll
    - unparam
    - dogsled
    - nakedret
    - prealloc
    - gocritic
    - testpackage
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    paths:
      - bin
      - hack
      - test
      - vendor
      - third_party
      - ".*generate\\.go$"
    rules:
      - linters:
          - gosec
        text: 'G(201):'
      # Exclude G101 for header name constants (false positives)
      - linters:
          - gosec
        text: 'G101:'
        path: "internal/(auth|authz)/constants\\.go"
      # Exclude lll for kubebuilder markers and long struct tags
      - linters:
          - lll
        source: "^//\\s*\\+kubebuilder:"
      - linters:
          - lll
        source: "`json:.*yaml:.*`"
      # Exclude lll for API types (kubebuilder annotations)
      # Exclude stuttering names - common in Go packages
      - linters:
          - revive
        text: "stutters"
      # Exclude unused-parameter for interface implementations
      - linters:
          - revive
        text: "unused-parameter"
      # Exclude if-return for validation functions
      - linters:
          - revive
        text: "if-return"
      # Exclude context-as-argument for specific patterns
      - linters:
          - revive
        text: "context-as-argument"
      # Exclude staticcheck QF1008 for embedded field selectors
      - linters:
          - staticcheck
        text: "QF1008"
      # Exclude gocritic importShadow for common patterns
      - linters:
          - gocritic
        text: "importShadow"
      # Exclude gocritic httpNoBody
      - linters:
          - gocritic
        text: "httpNoBody"
      # Exclude gocritic ifElseChain
      - linters:
          - gocritic
        text: "ifElseChain"
      # Exclude var-naming for util package (common helper package name)
      - linters:
          - revive
        text: "var-naming: avoid meaningless package names"
        path: "internal/util/"
  settings:
    errcheck:
      exclude-functions:
        - fmt.Fprintf
        - fmt.Fprint
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - wrapperFunc
        - paramTypeCombine
      settings:
        hugeParam:
          sizeThreshold: 512
        rangeValCopy:
          sizeThreshold: 512
    funlen:
      lines: 300
      statements: 90
    lll:
      line-length: 120
      tab-width: 4
    nestif:
      min-complexity: 7
    gocyclo:
      min-complexity: 27
    gocognit:
      min-complexity: 35
    goimports:
      local-prefixes: github.com/vyrodovalexey/avapigw
    misspell:
      locale: US
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: if-return
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
